#!/usr/bin/env python
import sys


def cli():
    value = ''
    try:
        # param name
        param_name = sys.argv[1]
        with open('/conf/%s' % param_name, 'r') as f:
            value = f.read()
    except:
        pass

    sys.stdout.write('%s' % value)
    sys.stdout.flush()


if __name__ == '__main__':
    cli()
