kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-secret-pod-crud
  namespace: default
subjects:
- kind: Group
  name: system:serviceaccounts:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-pod-crud
  apiGroup: rbac.authorization.k8s.io
