---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ow-offloadserver
spec:
  replicas: 1
  minReadySeconds: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: offloadserver
    spec:
      containers:
      - name: offloadserver
        image: docker5gmedia/ow-offload-server:c056640
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: OW_OFFLOAD_IMAGE
          value: docker5gmedia/ow-offload-server:c056640
        livenessProbe:
          httpGet:
              path: /hello
              port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
---
# Exposes Offload Service using NodePort
apiVersion: v1
kind: Service
metadata:
  labels:
    name: offloadservice
  name: ow-offloadservice
spec:
  ports:
  - port: 8080
    name: http-api
  selector:
    app: offloadserver
  type: NodePort
